@echo off
echo Copying files...
echo copy "vagrant_scripts\ubuntu_x64\Vagrantfile" "..\..\Vagrantfile"
copy "vagrant_scripts\ubuntu_x64\Vagrantfile" "..\..\Vagrantfile"
echo copy "vagrant_scripts\ubuntu_x64\run_bootstrap.sh" "..\..\run_bootstrap.sh"
copy "vagrant_scripts\ubuntu_x64\run_bootstrap.sh" "..\..\run_bootstrap.sh"
echo copy "vagrant_scripts\ubuntu_x64\bootstrap.sh" "..\..\bootstrap.sh" 
copy "vagrant_scripts\ubuntu_x64\bootstrap.sh" "..\..\bootstrap.sh"
echo mkdir "..\..\logs"
mkdir "..\..\logs"
echo copy "vagrant_scripts\ubuntu_x64\logs\vagrant_logs_readme.txt" "..\..\logs\vagrant_logs_readme.txt"
copy "vagrant_scripts\ubuntu_x64\logs\vagrant_logs_readme.txt" "..\..\logs\vagrant_logs_readme.txt"
echo copy "vagrant_scripts\common\md5test_ubuntu_pg_hba_conf.sh" "..\..\md5test_ubuntu_pg_hba_conf.sh"
copy "vagrant_scripts\common\md5test_ubuntu_pg_hba_conf.sh" "..\..\md5test_ubuntu_pg_hba_conf.sh"
echo copy "vagrant_scripts\common\md5test_ubuntu_postactivate.sh" "..\..\md5test_ubuntu_postactivate.sh"
copy "vagrant_scripts\common\md5test_ubuntu_postactivate.sh" "..\..\md5test_ubuntu_postactivate.sh"
echo copy "config_examples\pg_hba.conf.ubuntu.default" "..\..\pg_hba.conf.ubuntu.default"
copy "config_examples\pg_hba.conf.ubuntu.default" "..\..\pg_hba.conf.ubuntu.default"
echo copy "config_examples\pg_hba.conf.ubuntu.makahiki" "..\..\pg_hba.conf.ubuntu.makahiki"
copy "config_examples\pg_hba.conf.ubuntu.makahiki" "..\..\pg_hba.conf.ubuntu.makahiki"
echo copy "config_examples\postactivate.default" "..\..\postactivate.default"
copy "config_examples\postactivate.default" "..\..\postactivate.default"
echo copy "config_examples\postactivate.makahiki" "..\..\postactivate.makahiki"
copy "config_examples\postactivate.makahiki" "..\..\postactivate.makahiki"
echo Done.